package tse.pagerank.gui;

import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;

import tse.pagerank.model.Page;
import tse.pagerank.ordonnanceur.GrandManitou;

/**
 *
 * @author Thibaut GALLAIS & Arnaud LEDRU
 */
public class SwingGui extends javax.swing.JDialog 
{
	private List<Page> listeData;

    /**
     * Creates new form swingInterface
     */
    public SwingGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        listeData = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setText("Nom Categorie");

        jButton1.setText("Rechercher");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() 
        {
            public void mouseReleased(java.awt.event.MouseEvent evt) 
            {
                boutonClicked();
            	
            }
        });
        
        jList1.addMouseListener(new MouseAdapter() 
        {
            public void mouseClicked(MouseEvent evt) 
            {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {

                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    System.out.println(listeData.get(index));
                    try 
                    {
                    	String webPage = "https://simple.wikipedia.org/wiki/" + listeData.get(index).getNom().substring(1, listeData.get(index).getNom().length()-1);
                        openWebpage(new URI(webPage));
                    } catch (URISyntaxException e) 
                    {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }

                } else if (evt.getClickCount() == 3) {

                    // Triple-click detected
                    int index = list.locationToIndex(evt.getPoint());
                }
            }
        });
        String[] init = {"Bienvenue, veuillez entrer un nom ou un ID."};
        jList1.setListData(init);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }                    

     public void boutonClicked()
     {
    	 List<Page> listPages = new ArrayList<Page>();
    	 
    	try //Is an ID
    	{ 
    		int id = Integer.parseInt(jTextField1.getText());
    		listPages = GrandManitou.sortPages(GrandManitou.getAllPagesFromCat(id, null));
    	}
    	catch (NumberFormatException e) //Is a name 
    	{
			String nom = jTextField1.getText();
			if(GrandManitou.hashNomIdCat.get("'" + nom + "'") != null){
    		listPages = GrandManitou.sortPages(GrandManitou.getAllPagesFromCat("'" + nom + "'"));
			}else{
				JOptionPane.showMessageDialog(this, "Cette catégorie n'existe pas");
			}
		}
    	
    	listeData = listPages;
    	jList1.setListData(listToStringCrochet20(listPages)); 
     }
    
     
     private String[] listToStringCrochet20(List<Page> array){
    	 String[] res = new String[array.size()];
    	 
    	 for(int i=0; i<Math.min(array.size(), 20);i++){
    		 res[i] = Math.log10(array.get(i).getPageRanks()) + "   \t   " + array.get(i).getNom();
    	 }
    	 return res;
     }
     
     public static void openWebpage(URI uri) {
         Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
         if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
             try {
                 desktop.browse(uri);
             } catch (Exception e) {
                 e.printStackTrace();
             }
         }
     }

     public static void openWebpage(URL url) {
         try {
             openWebpage(url.toURI());
         } catch (URISyntaxException e) {
             e.printStackTrace();
         }
     }
    
    public static void launchGUI()
    {
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	SwingGui dialog = new SwingGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
